# Generated by Django 4.2.3 on 2023-07-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completado',
            field=models.BooleanField(default=False, verbose_name='Completada: '),
        ),
    ]
